### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by andymckay** [acdha/nose-congestion#2]
Any chance you could a license to the repo?

**Comment by acdha** [comment]
Sure - I'll add a public domain notice tomorrow.

Sent from my iPhone

On Dec 4, 2012, at 9:36 PM, Andy McKay notifications@github.com wrote:

Any chance you could a license to the repo?

—
Reply to this email directly or view it on
GitHubhttps://github.com/acdha/nose-congestion/issues/2.

**Comment by acdha** [comment]
See https://github.com/acdha/nose-congestion/blob/master/LICENSE

**Comment by andymckay** [comment]
Thanks
